server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wsn
    username: root
    password: frux258456 
  jpa:
    show-sql: true
    properties:
       hibernate:
          dialect: org.hibernate.dialect.MariaDB53Dialect
    hibernate:
       ddl-auto: update